version: "3"

services:
  newtube-frontend:
    container_name: newtube-frontend
    image: newtube.azurecr.io/newtube-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    env_file:
      - .env
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
